### ISSUE TITLE
Orga fixes

### ISSUE THREAD

**Issue by jaagut** [bit-bots/TORSO_21_dataset#6]
- [x] Add license #9 
- [x] Fix bibtex #7 
- [x] Add Citation file .cff #8 #10
- [x] Download script
- [x] Download link
- [x] Fix robot (and other detection) counts #14
- [ ] Fix segmentation field color value #12
- [ ] Readme: Add notes:
    - [ ] Limitation in Simulation: Annotations contain player number, even if only a small robot-part is visible
    - [ ] Limitation in Reality: Most robots are in rather small and in the upper half of the images because they are far away.
- [ ] Create git-tag
- [ ] Rebuild ZIP-Files
- [ ] Changelog
